name: Deploy API Gateway

on:
  push:
    branches:
      - main
    paths:
      - 'api_gateway/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.2.0

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3.1.2

    - name: Initialize Terraform
      run: terraform init
      working-directory: api_gateway

    - name: Validate Terraform
      run: terraform validate
      working-directory: api_gateway

    - name: Plan Terraform
      run: terraform plan
      working-directory: api_gateway

    - name: Apply Terraform
      run: terraform apply -auto-approve 
      working-directory: api_gateway