name: Deploy Lambda and API Gateway

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Lambda Repository
        uses: actions/checkout@v4.2.0
        with:
          repository: viniciussantos45/fast-food-tech-challenge-lambda

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.4
        with:
          node-version: "18"
  
      - name: Install Dependencies
        run: |
          cd lambda_auth
          npm install

      - name: Zip Lambda Function
        run: |
          cd lambda_auth
          zip -r ../lambda_auth.zip .

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: lambda_package
          path: lambda_auth.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4.2.0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2

      - name: Terraform Init for Lambda
        run: terraform init
        working-directory: lambda

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: lambda_package
          path: lambda_auth.zip

      - name: Terraform Plan for Lambda
        run: terraform plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        working-directory: lambda

      - name: Terraform Apply for Lambda
        run: terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        working-directory: lambda

      - name: Terraform Init for API Gateway
        run: terraform init
        working-directory: api_gateway

      - name: Terraform Apply for API Gateway
        run: terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        working-directory: api_gateway
